import { useState, useMemo, useCallback } from 'react';
import { ALL_COMMANDS, CATEGORIES, type CommandFull, type CommandArg, type ChainItem, type OS } from './commands';

// ============================================
// Constants
// ============================================

const OS_INFO: Record<OS, { name: string; icon: string }> = {
  all: { name: 'All', icon: '🌐' },
  linux: { name: 'Linux', icon: '🐧' },
  macos: { name: 'macOS', icon: '🍎' },
  windows: { name: 'Windows', icon: '🪟' },
};

const OPERATORS = [
  { id: '|', name: 'Pipe', desc: 'Pass output to next', color: 'bg-blue-500' },
  { id: '&&', name: 'And', desc: 'Run if prev succeeds', color: 'bg-green-500' },
  { id: '||', name: 'Or', desc: 'Run if prev fails', color: 'bg-amber-500' },
  { id: ';', name: 'Then', desc: 'Always run next', color: 'bg-slate-500' },
] as const;

// ============================================
// Utils
// ============================================

function buildCommandString(command: CommandFull, values: Record<string, unknown>): string {
  const parts: string[] = [command.base];
  const sorted = [...(command.args || [])].sort((a, b) => {
    if (a.positional && !b.positional) return 1;
    if (!a.positional && b.positional) return -1;
    if (a.positional && b.positional) return (a.position || 0) - (b.position || 0);
    return 0;
  });
  for (const arg of sorted) {
    const v = values[arg.id];
    if (arg.type === 'checkbox') {
      if (v === true && arg.flag) parts.push(arg.flag);
    } else if (v !== undefined && v !== '' && v !== null) {
      if (arg.positional) {
        const s = String(v);
        parts.push(s.includes(' ') ? `'${s}'` : s);
      } else if (arg.flag) {
        const s = String(v);
        if (arg.flag.endsWith('=') || arg.flag.endsWith(':')) {
          parts.push(`${arg.flag}${s}`);
        } else {
          parts.push(arg.flag, s.includes(' ') ? `'${s}'` : s);
        }
      }
    }
  }
  return parts.join(' ');
}

function parseToPyList(cmdStr: string): string {
  const parts: string[] = [];
  let cur = '', inQ = false, qc = '';
  for (let i = 0; i < cmdStr.length; i++) {
    const c = cmdStr[i];
    if (!inQ && (c === '"' || c === "'")) { inQ = true; qc = c; }
    else if (inQ && c === qc) { inQ = false; qc = ''; }
    else if (!inQ && c === ' ') { if (cur) { parts.push(cur); cur = ''; } }
    else cur += c;
  }
  if (cur) parts.push(cur);
  return '[' + parts.map(p => `"${p.replace(/"/g, '\\"')}"`).join(', ') + ']';
}

function generatePython(chain: ChainItem[]): string {
  if (!chain.length) return '';
  const L: string[] = [
    '#!/usr/bin/env python3',
    '"""', 'Generated by CliGUI — Cross-platform CLI Workflow',
    `Generated: ${new Date().toISOString().split('T')[0]}`, '"""', '',
    'import subprocess, sys',
    'from typing import Optional, Tuple', '',
    'def run(cmd: list[str], stdin: Optional[str] = None) -> Tuple[int, str, str]:',
    '    try:',
    '        r = subprocess.run(cmd, input=stdin, capture_output=True, text=True)',
    '        return r.returncode, r.stdout, r.stderr',
    '    except FileNotFoundError:',
    '        return 127, "", f"Command not found: {cmd[0]}"',
    '    except Exception as e:',
    '        return 1, "", str(e)', '', '',
    'def main():', '    code, out, err = 0, None, ""', '',
  ];
  for (let i = 0; i < chain.length; i++) {
    const it = chain[i];
    const cs = buildCommandString(it.command, it.values);
    const cp = parseToPyList(cs);
    L.push(`    # Step ${i + 1}: ${it.command.name}`);
    L.push(`    cmd = ${cp}`);
    if (i === 0) {
      L.push('    code, out, err = run(cmd)');
      L.push('    if err: print(err, file=sys.stderr, end="")');
    } else {
      const op = chain[i - 1].operator || ';';
      if (op === '|') {
        L.push('    code, out, err = run(cmd, stdin=out)');
      } else if (op === '&&') {
        L.push('    if code == 0:');
        L.push('        code, out, err = run(cmd)');
      } else if (op === '||') {
        L.push('    if code != 0:');
        L.push('        code, out, err = run(cmd)');
      } else {
        L.push('    code, out, err = run(cmd)');
      }
    }
    L.push('');
  }
  L.push('    if out: print(out, end="")');
  L.push('    return code');
  L.push('', '', 'if __name__ == "__main__":');
  L.push('    sys.exit(main())');
  return L.join('\n');
}

// ============================================
// App
// ============================================

export default function App() {
  const [selectedOS, setSelectedOS] = useState<OS>('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedCats, setExpandedCats] = useState<Set<string>>(new Set(['navigation', 'text', 'git']));
  const [selectedCmd, setSelectedCmd] = useState<CommandFull | null>(null);
  const [formValues, setFormValues] = useState<Record<string, unknown>>({});
  const [chain, setChain] = useState<ChainItem[]>([]);
  const [showHelp, setShowHelp] = useState(false);
  const [shellCopied, setShellCopied] = useState(false);
  const [pyCopied, setPyCopied] = useState(false);

  // Build index from embedded data
  const allCmds = useMemo(() => Object.values(ALL_COMMANDS), []);

  const filtered = useMemo(() => {
    return allCmds.filter(c => {
      const osOk = selectedOS === 'all' || c.os.includes(selectedOS);
      const qOk = !searchQuery || c.name.toLowerCase().includes(searchQuery.toLowerCase()) || c.description.toLowerCase().includes(searchQuery.toLowerCase());
      return osOk && qOk;
    });
  }, [allCmds, selectedOS, searchQuery]);

  const grouped = useMemo(() => {
    const g: Record<string, CommandFull[]> = {};
    for (const c of filtered) { if (!g[c.category]) g[c.category] = []; g[c.category].push(c); }
    return g;
  }, [filtered]);

  const initForm = useCallback((cmd: CommandFull) => {
    const vals: Record<string, unknown> = {};
    for (const a of cmd.args || []) {
      vals[a.id] = a.type === 'checkbox' ? (a.default ?? false) : (a.default ?? '');
    }
    setFormValues(vals);
  }, []);

  const selectCmd = useCallback((id: string) => {
    const cmd = ALL_COMMANDS[id];
    if (cmd) { setSelectedCmd(cmd); initForm(cmd); }
  }, [initForm]);

  const disabledArgs = useMemo(() => {
    if (!selectedCmd) return new Set<string>();
    const d = new Set<string>();
    for (const a of selectedCmd.args || []) {
      if (a.depends_on?.some(dep => !formValues[dep])) d.add(a.id);
      if (a.conflicts_with?.some(cid => formValues[cid])) d.add(a.id);
    }
    return d;
  }, [selectedCmd, formValues]);

  const updateVal = (id: string, value: unknown) => {
    const nv = { ...formValues, [id]: value };
    const arg = selectedCmd?.args?.find(a => a.id === id);
    if (arg?.conflicts_with && value) {
      for (const cid of arg.conflicts_with) {
        const ca = selectedCmd?.args?.find(a => a.id === cid);
        nv[cid] = ca?.type === 'checkbox' ? false : '';
      }
    }
    setFormValues(nv);
  };

  const addToChain = () => {
    if (!selectedCmd) return;
    setChain([...chain, { id: `${selectedCmd.id}-${Date.now()}`, command: selectedCmd, values: { ...formValues }, operator: '|' }]);
    initForm(selectedCmd);
  };

  const preview = selectedCmd ? buildCommandString(selectedCmd, formValues) : '';
  const chainStr = chain.map((it, i) => {
    const c = buildCommandString(it.command, it.values);
    return i < chain.length - 1 && it.operator ? `${c} ${it.operator}` : c;
  }).join(' ');
  const pyScript = useMemo(() => generatePython(chain), [chain]);

  const copyWithFeedback = async (text: string, setter: (v: boolean) => void) => {
    await navigator.clipboard.writeText(text);
    setter(true);
    setTimeout(() => setter(false), 500);
  };

  const download = () => {
    const b = new Blob([pyScript], { type: 'text/plain' });
    const u = URL.createObjectURL(b);
    const a = document.createElement('a');
    a.href = u; a.download = 'workflow.py'; a.click();
    URL.revokeObjectURL(u);
  };

  // Group args helper
  const getArgGroups = (args: CommandArg[]) => {
    const g: Record<string, CommandArg[]> = {};
    for (const a of args) { const k = a.group || 'Options'; if (!g[k]) g[k] = []; g[k].push(a); }
    return Object.entries(g);
  };

  return (
    <div className="h-screen flex flex-col bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 text-white overflow-hidden">
      {/* Header */}
      <header className="shrink-0 border-b border-slate-700/50 bg-slate-900/90 backdrop-blur-sm z-40">
        <div className="px-4 py-2.5 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <span className="text-2xl">⚡</span>
            <div>
              <h1 className="text-lg font-bold bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent leading-tight">CliGUI</h1>
              <p className="text-[10px] text-slate-500 leading-tight">Visual CLI Workflow Builder</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <span className="text-xs text-slate-500 hidden sm:block">{allCmds.length} commands</span>
            <button onClick={() => setShowHelp(true)} className="px-2.5 py-1 text-xs bg-slate-700/80 hover:bg-slate-600 rounded-md transition-colors">❓ Help</button>
          </div>
        </div>
      </header>

      {/* Main */}
      <div className="flex-1 flex min-h-0 p-3 gap-3">
        {/* Left — Library */}
        <div className="w-72 shrink-0 flex flex-col bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden">
          {/* Filters */}
          <div className="shrink-0 p-3 border-b border-slate-700/50 space-y-2.5">
            <h2 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">📚 Commands</h2>
            {/* OS */}
            <div className="flex flex-wrap gap-1">
              {(Object.keys(OS_INFO) as OS[]).map(os => (
                <button key={os} onClick={() => setSelectedOS(os)}
                  className={`px-2 py-0.5 text-[11px] rounded transition-all ${selectedOS === os ? 'bg-blue-500 text-white shadow-md shadow-blue-500/20' : 'bg-slate-700/50 text-slate-400 hover:bg-slate-700 hover:text-white'}`}>
                  {OS_INFO[os].icon} {OS_INFO[os].name}
                </button>
              ))}
            </div>
            {/* Search */}
            <div className="relative">
              <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-slate-500 text-xs">🔍</span>
              <input type="text" placeholder="Search..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)}
                className="w-full bg-slate-700/40 border border-slate-600/40 rounded-lg py-1.5 pl-8 pr-3 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500/50" />
              {searchQuery && <button onClick={() => setSearchQuery('')} className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-500 hover:text-white text-xs">✕</button>}
            </div>
          </div>
          {/* List */}
          <div className="flex-1 overflow-y-auto p-1.5">
            {CATEGORIES.sort((a, b) => a.order - b.order).map(cat => {
              const cmds = grouped[cat.id];
              if (!cmds?.length) return null;
              const exp = expandedCats.has(cat.id);
              return (
                <div key={cat.id} className="mb-1">
                  <button onClick={() => { const n = new Set(expandedCats); exp ? n.delete(cat.id) : n.add(cat.id); setExpandedCats(n); }}
                    className="w-full flex items-center gap-1.5 px-2.5 py-1.5 rounded-lg hover:bg-slate-700/40 transition-colors text-left">
                    <span className={`text-[10px] transition-transform ${exp ? 'rotate-90' : ''}`}>▶</span>
                    <span className="text-sm">{cat.icon}</span>
                    <span className="text-xs font-medium text-slate-200 flex-1">{cat.name}</span>
                    <span className="text-[10px] text-slate-500 bg-slate-700/40 px-1.5 py-0.5 rounded-full">{cmds.length}</span>
                  </button>
                  {exp && (
                    <div className="ml-3 mt-0.5 space-y-px">
                      {cmds.map(cmd => (
                        <button key={cmd.id} onClick={() => selectCmd(cmd.id)}
                          className={`w-full text-left px-2.5 py-1.5 rounded-md transition-all ${selectedCmd?.id === cmd.id ? 'bg-blue-500/15 border border-blue-500/40 text-blue-300' : 'hover:bg-slate-700/40 text-slate-300 border border-transparent'}`}>
                          <div className="flex items-center gap-1.5">
                            <code className="text-[11px] font-mono text-slate-300">{cmd.name}</code>
                            <div className="flex gap-0.5 ml-auto">
                              {cmd.os.map(o => <span key={o} className="text-[10px] opacity-40">{OS_INFO[o as OS]?.icon}</span>)}
                            </div>
                          </div>
                          <p className="text-[10px] text-slate-500 truncate mt-0.5">{cmd.description}</p>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              );
            })}
            {filtered.length === 0 && (
              <div className="text-center text-slate-500 text-xs py-8">No commands found</div>
            )}
          </div>
        </div>

        {/* Center — Config */}
        <div className="flex-1 flex flex-col bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden min-w-0">
          {!selectedCmd ? (
            <div className="flex-1 flex items-center justify-center">
              <div className="text-center text-slate-500">
                <div className="text-4xl mb-3">👈</div>
                <div className="text-sm">Select a command to configure</div>
                <p className="text-xs mt-1 text-slate-600">Browse categories or search</p>
              </div>
            </div>
          ) : (
            <>
              {/* Header */}
              <div className="shrink-0 px-4 py-3 border-b border-slate-700/50 bg-slate-800/80">
                <div className="flex items-center justify-between mb-1">
                  <h2 className="text-lg font-bold font-mono bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
                    {selectedCmd.name}
                  </h2>
                  <div className="flex gap-1 items-center">
                    {selectedCmd.danger_level === 'dangerous' && <span className="text-[10px] bg-red-500/20 text-red-400 px-1.5 py-0.5 rounded">⚠️ Dangerous</span>}
                    {selectedCmd.danger_level === 'caution' && <span className="text-[10px] bg-amber-500/20 text-amber-400 px-1.5 py-0.5 rounded">⚠️ Caution</span>}
                    {selectedCmd.os.map(o => <span key={o} className="text-[10px] px-1.5 py-0.5 bg-slate-700/50 rounded">{OS_INFO[o as OS]?.icon}</span>)}
                  </div>
                </div>
                <p className="text-xs text-slate-400">{selectedCmd.description}</p>
              </div>

              {/* Args */}
              <div className="flex-1 overflow-y-auto px-4 py-3">
                {getArgGroups(selectedCmd.args || []).map(([gName, args]) => (
                  <div key={gName} className="mb-5">
                    <h3 className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mb-2 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>{gName}
                    </h3>
                    <div className="space-y-1.5">
                      {args.map(arg => {
                        const dis = disabledArgs.has(arg.id);
                        const has = arg.type === 'checkbox' ? formValues[arg.id] === true : !!formValues[arg.id];
                        return (
                          <div key={arg.id}
                            className={`px-3 py-2.5 rounded-lg border transition-all ${dis ? 'opacity-30 border-slate-700/20 bg-slate-800/20 pointer-events-none' : has ? 'border-blue-500/30 bg-blue-500/5' : 'border-slate-700/40 bg-slate-800/20 hover:border-slate-600/50'}`}>
                            <div className="flex items-start gap-2 mb-1.5">
                              <div className="flex-1 min-w-0">
                                <label className="text-xs font-medium text-white flex items-center gap-1.5 flex-wrap">
                                  {arg.name}
                                  {arg.required && <span className="text-red-400 text-[10px]">*</span>}
                                  {arg.flag && <code className="text-[10px] bg-slate-700/80 px-1 py-px rounded text-blue-300 font-mono">{arg.flag}</code>}
                                  {arg.danger && <span className="text-[10px] text-red-400 bg-red-500/10 px-1 py-px rounded">danger</span>}
                                </label>
                                {arg.description && <p className="text-[10px] text-slate-500 mt-0.5">{arg.description}</p>}
                                {arg.warning && <p className="text-[10px] text-amber-400 mt-0.5">{arg.warning}</p>}
                              </div>
                              {/* Checkbox inline */}
                              {arg.type === 'checkbox' && (
                                <label className="flex items-center gap-1.5 cursor-pointer shrink-0 mt-0.5">
                                  <div className={`w-8 h-4 rounded-full transition-all relative cursor-pointer ${formValues[arg.id] ? 'bg-blue-500' : 'bg-slate-600'}`}
                                    onClick={() => updateVal(arg.id, !formValues[arg.id])}>
                                    <div className={`w-3 h-3 rounded-full bg-white absolute top-0.5 transition-all shadow ${formValues[arg.id] ? 'left-4.5' : 'left-0.5'}`} />
                                  </div>
                                </label>
                              )}
                            </div>
                            {arg.type === 'text' && (
                              <input type="text" value={String(formValues[arg.id] || '')} onChange={e => updateVal(arg.id, e.target.value)}
                                placeholder={arg.placeholder} disabled={dis}
                                className="w-full bg-slate-700/40 border border-slate-600/30 rounded py-1.5 px-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500/40 disabled:opacity-40" />
                            )}
                            {arg.type === 'number' && (
                              <input type="number" value={formValues[arg.id] !== undefined && formValues[arg.id] !== '' ? Number(formValues[arg.id]) : ''}
                                onChange={e => updateVal(arg.id, e.target.value ? Number(e.target.value) : '')}
                                placeholder={arg.placeholder} min={arg.min} max={arg.max} disabled={dis}
                                className="w-full bg-slate-700/40 border border-slate-600/30 rounded py-1.5 px-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500/40 disabled:opacity-40" />
                            )}
                            {arg.type === 'select' && (
                              <select value={String(formValues[arg.id] || '')} onChange={e => updateVal(arg.id, e.target.value)} disabled={dis}
                                className="w-full bg-slate-700/40 border border-slate-600/30 rounded py-1.5 px-2.5 text-xs text-white focus:outline-none focus:border-blue-500/40 disabled:opacity-40">
                                {arg.options?.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                              </select>
                            )}
                          </div>
                        );
                      })}
                    </div>
                  </div>
                ))}
                {/* Examples */}
                {selectedCmd.examples?.length ? (
                  <div className="mb-5">
                    <h3 className="text-[10px] font-semibold text-slate-400 uppercase tracking-widest mb-2 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-emerald-500"></span>Examples
                    </h3>
                    <div className="space-y-1.5">
                      {selectedCmd.examples.map((ex, i) => (
                        <button key={i} onClick={() => setFormValues(ex.values as Record<string, unknown>)}
                          className="w-full text-left px-3 py-2 bg-slate-700/20 border border-slate-600/20 rounded-lg hover:border-emerald-500/30 hover:bg-emerald-500/5 transition-colors">
                          <div className="text-xs font-medium text-white">{ex.name}</div>
                          <code className="text-[10px] text-emerald-400 font-mono">{ex.output}</code>
                        </button>
                      ))}
                    </div>
                  </div>
                ) : null}
              </div>

              {/* Preview + Add */}
              <div className="shrink-0 px-4 py-3 border-t border-slate-700/50 bg-slate-900/50">
                <div className="mb-2.5">
                  <label className="text-[10px] text-slate-500 mb-1 block uppercase tracking-wider">Preview</label>
                  <div className="px-3 py-2 bg-black/40 rounded-lg font-mono text-xs text-green-400 break-all min-h-[28px]">{preview || <span className="text-slate-600">Configure options above</span>}</div>
                </div>
                <button onClick={addToChain}
                  className="w-full py-2.5 bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white text-sm font-medium rounded-lg transition-all shadow-lg shadow-blue-500/20 hover:shadow-blue-500/30 active:scale-[0.98]">
                  ➕ Add to Workflow
                </button>
              </div>
            </>
          )}
        </div>

        {/* Right — Workflow */}
        <div className="w-80 shrink-0 flex flex-col bg-slate-800/50 rounded-xl border border-slate-700/50 overflow-hidden">
          <div className="shrink-0 px-3 py-2.5 border-b border-slate-700/50">
            <h2 className="text-xs font-semibold text-slate-400 uppercase tracking-wider flex items-center gap-1.5">
              🔗 Workflow
              {chain.length > 0 && <span className="text-[10px] bg-blue-500/20 text-blue-300 px-1.5 py-0.5 rounded-full ml-1">{chain.length}</span>}
            </h2>
          </div>

          {/* Chain */}
          <div className="flex-1 overflow-y-auto p-2.5">
            {chain.length === 0 ? (
              <div className="h-full flex items-center justify-center">
                <div className="text-center text-slate-600 text-xs">
                  <div className="text-3xl mb-2">🔗</div>
                  <div>Add commands to build</div>
                  <div className="mt-1 text-[10px]">your workflow chain</div>
                </div>
              </div>
            ) : (
              <div className="space-y-1.5">
                {chain.map((it, i) => (
                  <div key={it.id}>
                    <div className="px-2.5 py-2 bg-slate-700/25 border border-slate-600/25 rounded-lg group">
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-[11px] font-medium text-slate-200">{it.command.name}</span>
                        <button onClick={() => setChain(chain.filter((_, j) => j !== i))}
                          className="text-slate-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-all text-xs">✕</button>
                      </div>
                      <code className="text-[10px] text-green-400/80 font-mono block break-all leading-relaxed">{buildCommandString(it.command, it.values)}</code>
                    </div>
                    {i < chain.length - 1 && (
                      <div className="flex justify-center py-1">
                        <div className="flex gap-px bg-slate-800/80 rounded-md p-px">
                          {OPERATORS.map(op => (
                            <button key={op.id} onClick={() => { const c = [...chain]; c[i].operator = op.id as '|' | '&&' | '||' | ';'; setChain(c); }}
                              title={op.desc}
                              className={`px-2 py-1 text-[10px] font-mono rounded transition-all ${it.operator === op.id ? `${op.color} text-white shadow` : 'text-slate-500 hover:bg-slate-700 hover:text-slate-300'}`}>
                              {op.id}
                            </button>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Output */}
          {chain.length > 0 && (
            <div className="shrink-0 border-t border-slate-700/50">
              {/* Shell */}
              <div className="px-3 py-2.5">
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-[10px] text-slate-500 uppercase tracking-wider">Shell</label>
                  <button onClick={() => copyWithFeedback(chainStr, setShellCopied)}
                    className={`text-[10px] px-2 py-0.5 rounded transition-all ${shellCopied ? 'bg-green-500/20 text-green-400' : 'text-blue-400 hover:text-blue-300 hover:bg-blue-500/10'}`}>
                    {shellCopied ? '✓ Copied!' : '📋 Copy'}
                  </button>
                </div>
                <div className="px-2.5 py-1.5 bg-black/40 rounded font-mono text-[10px] text-green-400 break-all max-h-16 overflow-y-auto leading-relaxed">{chainStr}</div>
              </div>
              {/* Python */}
              <div className="px-3 py-2.5 border-t border-slate-700/30 bg-slate-900/40">
                <div className="flex gap-1.5 mb-2">
                  <button onClick={() => copyWithFeedback(pyScript, setPyCopied)}
                    className={`flex-1 py-1.5 text-[11px] rounded-md transition-all ${pyCopied ? 'bg-green-500/20 text-green-400 border border-green-500/30' : 'bg-slate-700/60 hover:bg-slate-600/60 text-white border border-slate-600/30'}`}>
                    {pyCopied ? '✓ Copied!' : '🐍 Copy Python'}
                  </button>
                  <button onClick={download}
                    className="flex-1 py-1.5 text-[11px] bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-500 hover:to-emerald-500 text-white rounded-md transition-all shadow shadow-green-500/20">
                    ⬇️ Download .py
                  </button>
                </div>
                <details className="text-[10px]">
                  <summary className="text-slate-500 cursor-pointer hover:text-slate-300 select-none">View Python script</summary>
                  <pre className="mt-1.5 p-2.5 bg-black/40 rounded text-green-400/80 overflow-x-auto max-h-40 overflow-y-auto font-mono leading-relaxed whitespace-pre">{pyScript}</pre>
                </details>
              </div>
              {/* Clear */}
              <div className="px-3 py-2 border-t border-slate-700/30">
                <button onClick={() => setChain([])}
                  className="w-full py-1.5 text-[11px] bg-red-500/8 hover:bg-red-500/15 text-red-400/80 rounded-md transition-colors border border-red-500/15">
                  🗑️ Clear Workflow
                </button>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Help Modal */}
      {showHelp && (
        <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4" onClick={() => setShowHelp(false)}>
          <div className="bg-slate-800 rounded-xl max-w-xl w-full max-h-[80vh] overflow-y-auto border border-slate-700 shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="p-5">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-lg font-bold text-white">How to Use CliGUI</h2>
                <button onClick={() => setShowHelp(false)} className="text-slate-400 hover:text-white text-xl leading-none">×</button>
              </div>
              <div className="space-y-4 text-slate-300 text-xs">
                <section>
                  <h3 className="text-sm font-semibold text-white mb-1"><span className="text-blue-400">1.</span> Select a Command</h3>
                  <p>Browse by OS or category. Search to find commands quickly. Click a command to load its options.</p>
                </section>
                <section>
                  <h3 className="text-sm font-semibold text-white mb-1"><span className="text-blue-400">2.</span> Configure Options</h3>
                  <p>Toggle flags, fill parameters. Conflicts auto-disable. Dependencies auto-show. Use examples for quick setup.</p>
                </section>
                <section>
                  <h3 className="text-sm font-semibold text-white mb-1"><span className="text-blue-400">3.</span> Build Workflow</h3>
                  <p>"Add to Workflow" chains commands. Pick operators between them:</p>
                  <div className="mt-2 space-y-1">
                    {OPERATORS.map(op => (
                      <div key={op.id} className="flex items-center gap-2">
                        <code className={`${op.color} text-white px-1.5 py-0.5 rounded text-[10px] font-mono`}>{op.id}</code>
                        <span><strong>{op.name}:</strong> {op.desc}</span>
                      </div>
                    ))}
                  </div>
                </section>
                <section>
                  <h3 className="text-sm font-semibold text-white mb-1"><span className="text-blue-400">4.</span> Export</h3>
                  <p>Copy the shell command or download a <strong>cross-platform Python script</strong> that works on Linux, macOS, and Windows.</p>
                </section>
                <section className="bg-slate-700/40 p-3 rounded-lg">
                  <h3 className="text-sm font-semibold text-white mb-1">📝 Contributing</h3>
                  <p>Commands are defined in <code className="bg-slate-600 px-1 rounded">src/commands.ts</code> and YAML files in <code className="bg-slate-600 px-1 rounded">public/commands/</code>. Clone the repo, add commands, and submit a PR!</p>
                </section>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
